[build]
  command = "npm run build"
  publish = "dist"

[dev]
  framework = "vite"

[[redirects]]
  from = "/api/*"
  to = "https://handwrittenletter.onrender.com/api/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET,HEAD,PUT,PATCH,POST,DELETE,OPTIONS"
    Access-Control-Allow-Headers = "X-CSRF-Token, X-Requested-With, Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, X-Api-Version, Authorization"
    Access-Control-Allow-Credentials = "true"
